version: "3.8"
services:
  train:
    image: leelabharathib/train:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  flight:
    image: leelabharathib/flight:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  bus:
    image: leelabharathib/bus:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: leelabharathib/recharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
